language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev gcc-6 g++-6
  - alias g++=g++-6
  - bash .build.amrex.sh ${DIM} nodeghostcells

install:
  - bash .build.sh ${DIM}

script:
  - bash .test.sh ${DIM}

env:
  - DIM=2
  - DIM=3
