language: generic

before_install:
  libraries:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev
  amrex:
  - pyenv global 3.6
  - mkdir amrex2d amrex3d
  - git clone https://github.com/AMReX-Codes/amrex.git
  - cd amrex
  - ./configure --dim=2 --prefix=../amrex2d/ --debug=yes
  - make
  - make install
  - make clean
  - rm -rf tmp_build_dir
  - ./configure --dim=3 --prefix=../amrex3d/ --debug=yes
  - make
  - make install
  - cd ..

jobs:
  include:
    - stage: 2d
      script: ./.build2d.sh
    - stage: 3d
      script: ./.build2d.sh

#script: bash ./.build.sh

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "brunnels@uccs.edu"
