language: generic

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "brunnels@uccs.edu"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev
  - bash .build.amrex.sh

jobs:
  include:
    - stage: compile-2d
      script: ./.build2d.sh
    - stage: compile-3d
      script: ./.build2d.sh

