language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --config gcc
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 
  - alias g++=g++-6
  - bash .build.amrex.sh ${DIM} nodeghostcells

install:
  - bash .build.sh ${DIM}

script:
  - bash .test.sh ${DIM}

env:
  - DIM=2
  - DIM=3
