language: generic

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "brunnels@uccs.edu"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev
  - bash .build.amrex.sh

jobs:
  include:
    - stage: Build2D
      script: bash ./.build2d.sh
    - stage: Test2D
      script: bash ./.test2d.sh
    - stage: Build3D
      script: bash ./.build3d.sh
