"""
Compare rotated Garrick Riemann simulations against the exact (stiffened-gas)
solution.

The set of angles is auto-discovered: the script globs
    ../input_Garrick_NN
relative to itself, parses NN out of each filename, and plots whichever of
those have a corresponding output directory under bin/. So you can run any
subset of the angled inputs and the script will plot exactly that subset --
add new input_Garrick_NN files (e.g. NN=22, 67) and they get picked up
automatically too.

For each discovered angle theta this:
  1. Loads the hydro2 output from bin/.../Angled/output_Garrick_Angled_NN
  2. Casts a yt ray along n = (cos theta, sin theta) through the origin.
  3. Plots density, normal velocity (u.n = vx*cos theta + vy*sin theta),
     and pressure against the signed normal coordinate s = x*cos theta + y*sin theta.

The exact 1D Riemann solution (from Garrick.hdf5, generated by
../../reference/Riemann_Garrick.py) is overlaid as a black solid line on each panel.
"""

import glob
import os
import re

import h5py
import matplotlib.pyplot as plt
import numpy as np
import yt

yt.funcs.mylog.setLevel(40)

# ============================================================================
# USER CONFIGURATION
# ============================================================================

# This script lives at tests/FlowRiemannUnitTests/Angled/reference/.
# AMReX writes outputs under bin/, so go up four levels.
output_dir_template = r'..\..\..\..\bin\tests\FlowRiemannUnitTests\Angled\output_Garrick_Angled_{:02d}'

# Where to look for input files when auto-discovering angles. Resolved relative
# to this script's location so it works regardless of where python is invoked.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
input_glob_pattern = os.path.join(_SCRIPT_DIR, '..', 'input_Garrick_*')
_input_re = re.compile(r'^input_Garrick_(\d+)$')

# Exact solution lives in the parent (non-angled) reference directory.
exact_hdf5_path = r'..\..\reference\Garrick.hdf5'
exact_group     = 'Garrick'

output_folder   = r'./Images'
output_filename = 'Garrick_Angled_overlay'

# Half-length of the sampling ray along n. Stays inside [-1, 1]^2 as long as
# S_MAX * max(|cos theta|, |sin theta|) <= 1, i.e. S_MAX <= 1.
S_MAX = 0.99

# ============================================================================

print("=" * 60)
print("OVERLAYING ROTATED GARRICK RIEMANN PROFILES vs EXACT")
print("=" * 60)

# ---------------------------------------------------------------------------
# Auto-discover angles: parse all input_Garrick_NN filenames, then keep only
# those whose simulation output directory exists.
# ---------------------------------------------------------------------------
_all_angles = sorted({
    int(m.group(1))
    for f in glob.glob(input_glob_pattern)
    for m in [_input_re.match(os.path.basename(f))]
    if m
})

if not _all_angles:
    raise SystemExit(f"No input_Garrick_NN files found at {input_glob_pattern}")

ANGLES = [theta for theta in _all_angles
          if os.path.isdir(output_dir_template.format(theta))]

if not ANGLES:
    raise SystemExit(
        f"Found {len(_all_angles)} input file(s) ({_all_angles}) but no matching "
        f"output directories. Run the simulations first (RUN_ANGLED.bash)."
    )

skipped = [a for a in _all_angles if a not in ANGLES]
print(f"Discovered angles from input files: {_all_angles}")
print(f"  -> with completed runs: {ANGLES}")
if skipped:
    print(f"  -> no output yet (skipping): {skipped}")

# ---------------------------------------------------------------------------
# Load exact solution
# ---------------------------------------------------------------------------
if not os.path.isfile(exact_hdf5_path):
    raise SystemExit(
        f"Exact-solution file not found: {exact_hdf5_path}\n"
        f"Generate it first by running ../../reference/Riemann_Garrick.py"
    )

with h5py.File(exact_hdf5_path, 'r') as f:
    if exact_group not in f:
        raise SystemExit(f"Group '{exact_group}' not in {exact_hdf5_path}; "
                         f"available: {list(f.keys())}")
    g = f[exact_group]
    s_exact   = g['xvec'][:]
    rho_exact = g['density'][:]
    u_exact   = g['velocity'][:]
    p_exact   = g['pressure'][:]
    u_star    = float(g['u_star'][()])

print(f"Loaded exact solution from {exact_hdf5_path}: {len(s_exact)} samples, "
      f"u_star = {u_star:.4f}")

# ---------------------------------------------------------------------------
# Plot setup
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(3, 1, figsize=(12, 14))
colors = plt.cm.viridis(np.linspace(0.0, 0.9, len(ANGLES)))

# Exact first (under the numerical curves)
exact_kwargs = dict(color='k', linewidth=2.5, linestyle='-', label='Exact', zorder=10)
axes[0].plot(s_exact, rho_exact, **exact_kwargs)
axes[1].plot(s_exact, u_exact,   **exact_kwargs)
axes[2].plot(s_exact, p_exact,   **exact_kwargs)

t_final = None
loaded = 0

for color, theta_deg in zip(colors, ANGLES):
    amrex_output_dir = output_dir_template.format(theta_deg)

    plot_files = sorted(
        os.path.join(amrex_output_dir, item)
        for item in os.listdir(amrex_output_dir)
        if os.path.isdir(os.path.join(amrex_output_dir, item)) and item.endswith('cell')
    )
    if not plot_files:
        print(f"  [skip] theta={theta_deg:>2d}deg: no *cell directories")
        continue

    last_plot = plot_files[-1]
    ds = yt.load(last_plot)
    if t_final is None:
        t_final = float(ds.current_time)

    theta = np.deg2rad(theta_deg)
    cth, sth = np.cos(theta), np.sin(theta)

    ray_start = ds.arr([-S_MAX * cth, -S_MAX * sth, 0.0], 'code_length')
    ray_end   = ds.arr([ S_MAX * cth,  S_MAX * sth, 0.0], 'code_length')
    ray = ds.ray(ray_start, ray_end)

    x   = np.array(ray['x'])
    y   = np.array(ray['y'])
    vx  = np.array(ray['velocityx'])
    vy  = np.array(ray['velocityy'])
    p   = np.array(ray['pressure'])
    rho = np.array(ray['density'])

    s   = x * cth + y * sth
    u_n = vx * cth + vy * sth

    order = np.argsort(s)
    s, rho, u_n, p = s[order], rho[order], u_n[order], p[order]

    label = f'theta = {theta_deg:>2d} deg'
    axes[0].plot(s, rho, '--', color=color, linewidth=1.3, label=label, alpha=0.85)
    axes[1].plot(s, u_n, '--', color=color, linewidth=1.3, label=label, alpha=0.85)
    axes[2].plot(s, p,   '--', color=color, linewidth=1.3, label=label, alpha=0.85)

    print(f"  [ok]   theta={theta_deg:>2d}deg: {len(s)} samples, "
          f"t = {float(ds.current_time):.6f}, "
          f"rho in [{rho.min():.4f}, {rho.max():.4f}], "
          f"p in [{p.min():.4e}, {p.max():.4e}]")
    loaded += 1

if loaded == 0:
    print("\nNo numerical datasets loaded - check that the simulations have run.")
    raise SystemExit(1)

title = (f'Rotated Garrick Riemann - exact (black) vs hydro2 at theta in {ANGLES} deg, '
         f't = {t_final:.4f} s')
axes[0].set_title(title, fontsize=14, fontweight='bold')

axes[0].set_xlabel(r'normal coordinate $s = x\cos\theta + y\sin\theta$', fontsize=12)
axes[0].set_ylabel(r'Density (kg/m$^3$)', fontsize=12)
axes[0].legend(fontsize=9, ncol=2)
axes[0].grid(True, alpha=0.3)
axes[0].set_xlim([-S_MAX, S_MAX])

axes[1].set_xlabel(r'normal coordinate $s$', fontsize=12)
axes[1].set_ylabel(r'Normal velocity $u_n = v_x\cos\theta + v_y\sin\theta$ (m/s)',
                   fontsize=12)
axes[1].legend(fontsize=9, ncol=2)
axes[1].grid(True, alpha=0.3)
axes[1].set_xlim([-S_MAX, S_MAX])

axes[2].set_xlabel(r'normal coordinate $s$', fontsize=12)
axes[2].set_ylabel(r'Pressure (Pa)', fontsize=12)
axes[2].legend(fontsize=9, ncol=2)
axes[2].grid(True, alpha=0.3)
axes[2].set_xlim([-S_MAX, S_MAX])

plt.tight_layout()

os.makedirs(output_folder, exist_ok=True)
output_path = os.path.join(output_folder, output_filename)
plt.savefig(output_path + '.png', format='png', dpi=300, bbox_inches='tight')
plt.savefig(output_path + '.eps', format='eps', bbox_inches='tight')

print(f"\nOverlay saved:")
print(f"  {output_path}.png")
print(f"  {output_path}.eps")

plt.show()

# ---------------------------------------------------------------------------
# Error metrics: L2 / Linf of each angle vs the exact solution, interpolated
# onto the numerical sample points along s.
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("ERROR METRICS vs EXACT (per angle)")
print("=" * 60)
print(f"{'theta':>6s}  {'rho L2':>12s} {'rho Linf':>12s}  "
      f"{'u_n L2':>12s} {'u_n Linf':>12s}  "
      f"{'p L2':>12s} {'p Linf':>12s}")

for theta_deg in ANGLES:
    amrex_output_dir = output_dir_template.format(theta_deg)
    plot_files = sorted(
        os.path.join(amrex_output_dir, item)
        for item in os.listdir(amrex_output_dir)
        if os.path.isdir(os.path.join(amrex_output_dir, item)) and item.endswith('cell')
    )
    if not plot_files:
        continue
    ds = yt.load(plot_files[-1])
    theta = np.deg2rad(theta_deg)
    cth, sth = np.cos(theta), np.sin(theta)
    ray = ds.ray(ds.arr([-S_MAX * cth, -S_MAX * sth, 0.0], 'code_length'),
                 ds.arr([ S_MAX * cth,  S_MAX * sth, 0.0], 'code_length'))
    x   = np.array(ray['x'])
    y   = np.array(ray['y'])
    s   = x * cth + y * sth
    rho = np.array(ray['density'])
    u_n = np.array(ray['velocityx']) * cth + np.array(ray['velocityy']) * sth
    p   = np.array(ray['pressure'])
    order = np.argsort(s)
    s, rho, u_n, p = s[order], rho[order], u_n[order], p[order]

    rho_ref = np.interp(s, s_exact, rho_exact)
    u_ref   = np.interp(s, s_exact, u_exact)
    p_ref   = np.interp(s, s_exact, p_exact)

    print(f"{theta_deg:>5d}d  "
          f"{np.linalg.norm(rho - rho_ref):>12.4e} {np.max(np.abs(rho - rho_ref)):>12.4e}  "
          f"{np.linalg.norm(u_n - u_ref):>12.4e} {np.max(np.abs(u_n - u_ref)):>12.4e}  "
          f"{np.linalg.norm(p - p_ref):>12.4e} {np.max(np.abs(p - p_ref)):>12.4e}")

print("=" * 60)
print(f"Done. {loaded}/{len(ANGLES)} angles plotted against exact.")
