name: Linux Build and Test

on: [push, pull_request]

jobs:
  test-2d:
    name: Build & Test (2D)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: configure (2d)
      run: ./configure --dim=2 
    - name: make
      run: make
    - name: test
      run: ./bin/test-2d-g++
  test-3d:
    name: Build & Test (3D)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: configure
      run: ./configure --dim=3 
    - name: make
      run: make
    - name: test
      run: ./bin/test-3d-g++
  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: [test-2d, test-3d]
    steps:
    - uses: actions/checkout@v2
    - uses: mpi4py/setup-mpi@v1
    - run: scripts/runtests.py
